# Generated by Django 3.1 on 2020-08-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200821_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
