# Generated by Django 3.1 on 2020-08-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200823_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='haiku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.haiku'),
        ),
        migrations.AlterField(
            model_name='haiku',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haikus', to='api.movie'),
        ),
    ]
