# Generated by Django 3.1 on 2020-08-24 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20200823_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='haiku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='api.haiku'),
        ),
        migrations.AlterField(
            model_name='haiku',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='haikus', to='api.movie'),
        ),
        migrations.AlterField(
            model_name='haiku',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='haikus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/blank-profile.png', upload_to='images/'),
        ),
    ]
