# Generated by Django 3.1 on 2020-08-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200825_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
    ]
