# Generated by Django 3.1 on 2020-08-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200825_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Poster',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Title',
            new_name='title',
        ),
    ]
